### ISSUE TITLE
Parser object and type errors

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/midi-to-part-mp3s#11]
I don't know if you're experiencing the same, but when my editor checks the static types (using `mypy` behind the scenes) it can't infer the types.

![Screen Shot 2019-06-21 at 15 29 16](https://user-images.githubusercontent.com/151206/59925928-721c1300-9439-11e9-82b2-2a72448f38e6.png)

**Comment by oli-ver** [comment]
I use Visual Studio Code with the linter Pep8. It does not show an error here:

![grafik](https://user-images.githubusercontent.com/965863/59944461-1c5d6000-9465-11e9-8ada-ae8abebc32e9.png)

Using mypy I get the same error:

![grafik](https://user-images.githubusercontent.com/965863/59944575-67777300-9465-11e9-99d5-98ab054f6e54.png)

You can ignore this error by a mypy comment:

`instrumental_volume_ratio = accompaniment_volume_ratio * args.instrumental_volume  # type: ignore `
Or you can use the dictionary variant for the argument parser (but code changes just because the linter cannot understand ArgumentParsers.... :) : 

`instrumental_volume_ratio = accompaniment_volume_ratio * vars(args)['instrumental-volume']`

**Comment by jackkinsella** [comment]
Correct me if I'm wrong, but isn't `mypy` the only tool that has static type inference, i.e. it's the only one that is currently type-aware? I got the impression from: https://www.python.org/dev/peps/pep-0484/

Therefore if we use type hints in the code, it's our responsibility to ensure zero complaints from `mypy`  – otherwise the code would seem sloppy to other contributors.

We had no type errors back in fae0a85b1f43dae301306d3be9e1e11a52005155. Unfortunately, a side effect of introducing the `args` global was confusing the static type checker.

I wonder if we could take a shortcut (for now) of using an `Any` type on args?
