### ISSUE TITLE
Documentation/Convention: Code formatter

### ISSUE THREAD

**Issue by jackkinsella** [jackkinsella/midi-to-part-mp3s#14]
We're getting noise in our commit messages due to our editors not being aligned in how to format the code. 

Could you pick a mainstream Python standard tool and update the README?

**Comment by oli-ver** [comment]
What do you mean with "noise"? Did I commit format changes by mistake?

Ok, so I should just decide for something? The default in VSCode is formatting with autopep8.

Should I reformat all our files once using this and commit this as a pull request? If you use Autopep8 also afterwards, there shouldn't be any formatting changes. I tried not to format the main script because every line will change because of this.

**Comment by jackkinsella** [comment]
I accidentally generated a bunch of minor format changes unrelated to the topic of a commit earlier this week because my editor's default was different to yours (I use VIM).

I will tell it to use `autopep8` behind the scenes now.  I assume you're using the default settings with no overrides?

Yes, please do a reformat on the big file. In review I'll make sure my editor formats it the same way.

**Comment by oli-ver** [comment]
Ok, I will add this to the README.md and create a pull request for the Python code.
For HTML/CSS/JavaScript in #10 I will use [js-beautify](http://jsbeautifier.org/) (through [HookyQR Beautify](https://marketplace.visualstudio.com/items?itemName=HookyQR.beautify) in VSCode). It will be added to the README.md when merging #10.

**Comment by oli-ver** [comment]
Can the pull request be closed?
